apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    app: wordpress
    tier: mysql
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath: # Might need to be nfs
    path: /mysql
