apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - nodePort: 31004
      port: 80
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
