apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  labels:
    app: wordpress
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath: # Might need to be nfs
    path: /html
