# k create -f hello-deploy.yaml --record
# Apply updates to existing deployment
# and trigger rollout:
# k apply -f hello-deploy.yaml
# Show status of rollout:
# k rollout status deploy hello-deploy --record=true
# List rolled out pods:
# k get pods
# List revisions:
# k rollout history deploy hello-deploy
# Rollback:
# k rollout undo deploy hello-deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 2
  minReadySeconds: 10 # Ensure pods healthy for 10 secs before taking down the next pod
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: RollingUpdate
    rollingUpdate: # Take 1 down at a time
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-pod
          image: nigelpoulton/pluralsight-docker-ci:latest
          ports:
            - containerPort: 8080
