# create –f job-definition.yaml
# kubectl get jobs
# kubectl get pods
# kubectl logs math-add-job-ld87pn
# k describe job # view number of success/failure and pod creates

apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 # Run this job until you get this many successes
  parallelism: 3 # Run this many pods in parallel
  backoffLimit: 15 # How many failures before back off
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ["expr", "3", ‘+', ‘2’]
      restartPolicy: Never # <-- only run once
