apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-replication-controller
spec:
  replicas: 2 # number of pods to spin up
  selector:
    app: hello-world
  template: # Embedded pod spec here
    metadata:
      labels:
        app: hello-world # matches the selector above
    spec:
      containers:
      - name: hello-pod
        image: nigelpoulton/pluralsight-docker-ci:latest
        ports:
        - containerPort: 8080

# Another example
apiVersion: V1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
  spec:
    containers:
      - name: nginx-container
        image: nginx
