# You'll be able to curl the NodePort Service
# by requesting `curl <NodeIP>:<NodePort>` (use IP of node cluster not np service)

apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      # By default, the `targetPort` is set to the same value as the `port` field.
      port: 80
      targetPort: 80
  selector: # Copy labels from pod pod.metadata.labels
    app: myapp
    type: front-end

# Imperitive create
# k expose deploy webapp-deploy --type=NodePort --name=webapp-svc --target-port=8080  --dry-run -o yaml > webapp-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    name: simple-webapp