apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: foo
      imagePullPolicy: Never
      env:
        - name: APP_COLOR
          value: blue
        - name: APP_URL
          value: http://example.com
