apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      # image: docker.io/dereckrx/ubuntu-sleeper
      imagePullPolicy: Never
