apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      imagePullPolicy: Never
      # command: ["sleep2.0"]
      args: ["5"]
